### ISSUE TITLE
Support to Concourse

### ISSUE THREAD

**Issue by jzimermann** [ccmenu/ccmenu#106]
Hey @erikdoe,

Very recently Concourse team released version 5.x that finally exposes the `cc.xml` endpoint. In order to access the projects, you could do something similar to that:

```
https://{{host}}/api/v1/teams/{{team}}/cc.xml
```

I'm trying to configure CCMenu to work with the Concourse instance we have here in my company but the authentication seems to depend on a specific Cookie that comes from a third-party authentication tool.

Do you have any idea if CCMenu should work under these conditions? 

Cheers,

**Comment by spinningarrow** [comment]
You'll have to run a local proxy. Examples:
- Using Node.js: https://gist.github.com/cburgmer/e22a3c078502606a8cb7e72fbf1d1713
- Using Caddy: https://gist.github.com/spinningarrow/f22e0aaacc2ed74465e01c6b146d614d
