### ISSUE TITLE
[BUG] Got a error appending a branch parameter to existing project url

### ISSUE THREAD

**Issue by sorakrisc** [ccmenu/ccmenu#118]
# [BUG] Got a error appending a branch parameter to existing project url
Unable to retrieve status of a project when branch parameter is added to existing project

with error "An error occurred when retrieving the project status. No project information provided by server."

![Screen Shot 2565-11-24 at 11 20 47](https://user-images.githubusercontent.com/91938916/203693773-1d1dd4e9-8849-451a-97c8-b6a0d11d6d96.png)

## Expected behavior 
Able to retrieve the server status.

## Actual behavior
Unable to retrieve the project status with error above.

## How to reproduce
1. Add a new project with `https://cc.buildkite.com/[organization-slug]/[pipeline-slug].xml?access_token=xxx` in feed url
2. Select "Use URL as entered above" and select "Continue"
4. Edit the same project with branch parameter `https://cc.buildkite.com/[organization-slug]/[pipeline-slug].xml?branch=master&access_token=xxx`

## Work around
Delete the project and add again with branch parameter

**Comment by erikdoe** [comment]
What happens when you try to retrieve the information with `curl`? Does that work?

```
curl https://cc.buildkite.com/[organization-slug]/[pipeline-slug].xml?branch=master&access_token=xxx
```
